{% set version = '0.7.8' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pegboard
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/carpentries/pegboard/archive/refs/tags/{{ version }}.tar.gz
  sha256: 52b390cf1d8275e6222e509366dbcc27655c4209a9e5f497c891516fff488c4c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-commonmark
    - r-fs >=1.5.0
    - r-glue
    - r-purrr
    - r-tinkr >=0.3.0
    - r-xml2
    - r-xslt
    - r-yaml
  run:
    - r-base
    - r-r6
    - r-commonmark
    - r-fs >=1.5.0
    - r-glue
    - r-purrr
    - r-tinkr >=0.3.0
    - r-xml2
    - r-xslt
    - r-yaml

test:
  requires:
    - r-testthat
    - r-gert
    - r-dplyr
  source_files:
    - tests/
  commands:
    - $R -e "library('pegboard')"                                                     # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('pegboard')\""                                            # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/carpentries/pegboard
  dev_url: https://github.com/carpentries/pegboard
  doc_url: https://carpentries.github.io/pegboard/
  license: MIT
  summary: Parse Source Files in The Carpentries Workbench
  description: |
    The Carpentries (<https://carpentries.org>) curricula is made of of lessons that are
    hosted as websites. Each lesson represents between a half day to two days of instruction
    and contains several episodes, which are written as 'kramdown'-flavored 'markdown'
    documents and converted to HTML using the 'Jekyll' static website generator. This
    package builds on top of the 'tinkr' package; reads in these markdown documents
    to 'XML' and stores them in R6 classes for convenient exploration and manipulation
    of sections within episodes.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - matthewfeickert
